[package]
name = "ksni-dummy"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["poly000"]
description = "dummy package to bypass cargo dependency check"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
